# nelmio_api_doc:
#     documentation:
#         info:
#             title: RepoFinder API
#             description: This is the API documentation for RepoFinder.
#             version: 1.0.0
#     areas: # to filter documented areas
#         path_patterns:
#             - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        info:
            title: RepoFinder API
            description: This is the API documentation for RepoFinder.
            version: 1.0.0
        servers:
            - url: http://localhost:8000
    areas:
        default:
            path_patterns: [ ^/api, ^/repositories ]
    models:
        use_jms: false
    media_types:
        json: application/json
    use_validation_groups: true
