controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# nelmio_api_doc:
#     resource: '@NelmioApiDocBundle/Resources/config/routing.yaml'
#     prefix: /api/doc
nelmio_api_doc:
    path: /api/doc
    controller: nelmio_api_doc.controller.swagger_ui